name: Build documentation

on:
  push:
    branches:
      - main

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@61704e23fa97c0502ce5355c489c6bec4194bff1  # main
    with:
      commit_sha: ${{ github.sha }}
      package: context-course
      package_name: context-course
      path_to_docs: context-course/units/
      additional_args: --not_python_module
      languages: en
    secrets:
      hf_token: ${{ secrets.HF_DOC_BUILD_PUSH }}
